### ISSUE TITLE
Build snpguest for Windows

### ISSUE THREAD

**Issue by nicopal** [virtee/snpguest#60]
Hi, 

I am facing some issues building snpguest for windows - looks like crate msru only supports Linux: https://docs.rs/msru/latest/msru/

Are there any plans to make snpguest windows-compatible?

Thanks.

**Comment by tylerfanelli** [comment]
Most of this crate is Linux-only. The underlying sev crate that we use for building most of this tool is Linux-only. I don't know if there exists an equivalent for windows.

**Comment by nicopal** [comment]
Thanks for saving my time, I was next considering to look into sev to see if that can be built for windows. 

Have you considered providing support/build an alternative for windows or is that too far off and am I the only one asking about it? The (sad) reality is that there are so many proprietary enterprise applications running on windows servers, would be a pity if attestation support would not be available for this large chunk of the market.

**Comment by larrydewey** [comment]
@nicopal unfortunately reading an MSR from user-space is not easily done on Windows (which is why `msru` doesn't offer windows support). Also, like @tylerfanelli mentioned, this tool is primarily Linux only due to the way we interact with the device drivers. It isn't to say we won't accept PRs adding needed support.

**Comment by nicopal** [comment]
Thank you, we will check internally if we can prioritise this now (or near future). Adding windows support could be useful in several cases.
