### ISSUE TITLE
--tcb_version option in snpguest key command seems to encompass the boot loader version only

### ISSUE THREAD

**Issue by aadomn** [virtee/snpguest#76]
I'm running an SEV-SNP guest using the snp.sh script from [sev-utils](https://github.com/amd/sev-utils) on an AMD EPYC 7313P platform.

While playing with the `snpguest key` command, I encountered a behavior I did not expect.
I'm running the following command:
`snpguest key derived-key.bin vcek --guest_file_select 100000 --tcb_version 4`
Which seems to work as expected (i.e. the derived key looks random) as long as `--tcb_version` takes an argument between 0 and 4.
However, if I provide a value outside this range, the resulting key is always null (i.e. consists of 0s only).

According to the [SEV-SNP firmware ABI spec](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf#%5B%7B%22num%22%3A138%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C62%2C553%2C0%5D):

> The TCB version to mix into the derived key. Must not exceed CommittedTcb.

From the attestation report, in my case the committed TCB is:
```
Committed TCB:

TCB Version:
  Microcode:   213
  SNP:         22
  TEE:         0
  Boot Loader: 4
```
Having the boot loader version equals to 4 seems to explain why I get a null key when providing a `tcb_version` larger than 4.
Still, I would have expected the command to handle the entire TCB version, i.e. in this case it would correspond to the following value in hexadecimal [according to the spec](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf#page=18):
`0xd516000000000004` which in base 10 equals `15354459979566284804`.

5 does not exceed 15354459979566284804, so by strictly following the spec I would have expected the key derivation to be successful.
Overall, I find a bit unclear what should be exactly passed as input to `--tcb_version`. Should it be the boot loader version only?

Thanks in advance for your support!

**Comment by DGonzalezVillal** [comment]
Hello @aadomn 

Thank you for raising the issue. I guess there should be a better explanation on how to pass in TCB values. Think of the TCB_VERSION (and most of the u64 bit structures on the tooling for that matter) as smaller parameters put into one big input.

So the [sev-snp spec](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf#page=18) defines the TCB as:

Microcode: bits 63:56 (8 bits)
SNP: bits 55:48 (8 bits)
Reserved: bits 47:16 (32 bits)
TEE: bits 15:8 (8 bits)
Boot Loader: bits 7:0 (8 bits)

So you're input will look something like this:

00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
(Micro)     (SNP)        (                          RESERVED                     )  (   TEE    ) (  BOOT   )

So the decimal or hex number that you pass in, you have to make sure that EACH of the sections is under each of the TCB minimums.

So when you are passing 5 for example, your input in bits will look like:
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000101
[     0     ]   [      0     ]                                                                    [     0     ]   [       5     ]
(Micro)     (SNP)        (                          RESERVED                     )  (   TEE    ) (  BOOT   )

So you see, even if 5 as a decimal is smaller than 15354459979566284804 it is an invalid parameter, because you're passing an invalid BOOT LOADER version.

So let's say you wanted to play around with different values for your TCB, then you would individually target each component. For example:
01100101 00010010 00000000 00000000 00000000 00000000 00000000 00000100
[     101   ]   [     18   ]                                                                    [     0     ]   [       4     ]
(Micro)     (SNP)        (                          RESERVED                     )  (   TEE    ) (  BOOT   )

And that decimal number is 7282883547411513348 and it should work just fine.

Looking back at it, this might not be the best way of passing those values, maybe a rework to make this simpler could be a good idea. But that is basically the way of using the tcb_version.

**Comment by aadomn** [comment]
Makes sense, thanks for your detailed explanation!
